/**
 * Browser-only facade for Lumen's same-origin AI proxy.
 *
 * Deliberately never accepts an API key or model name: those are server-owned
 * settings. Keeping this boundary narrow prevents credentials from entering a
 * Vite bundle, IndexedDB backup, browser log, or network request to another host.
 */

import { AI_REQUEST_CONTRACT_ID } from "./aiContract.js";

export const AI_TASKS = Object.freeze([
  "tutor",
  "explain",
  "socratic",
  "quiz",
  "flashcards",
  "interview",
  "summarize",
  "study_plan",
  "answer_feedback",
  "code_review",
]);

export const AI_DATA_DISCLOSURE = Object.freeze({
  destination: "the local Ollama model running on the Lumen server",
  sent: Object.freeze([
    "Your AI prompt",
    "The curriculum excerpt you choose to include",
    "Its document title",
    "Your selected difficulty level",
    "An optional bounded summary of older conversation turns",
    "The bounded conversation history for this session",
  ]),
  neverSentByThisClient: Object.freeze([
    "An OpenAI, Anthropic, Google, or other paid AI API key",
    "Unselected notes or documents",
    "Your complete local study profile",
    "Whiteboards, bookmarks, or review history unless you explicitly place them in the prompt or context",
  ]),
  webSearch: Object.freeze({
    default: "off",
    consent: "Web search runs only when you explicitly enable it for that request.",
    destination: "The self-hosted SearXNG service configured by the Lumen server, followed by the search engines enabled by its operator.",
    sent: "A bounded number of focused queries generated by the local model from the prompt, selected context, and bounded conversation history. If the model skips its required tool call, Lumen uses a bounded form of the learner's question so the authorized fallback still works. Query text can reproduce words or short fragments from those inputs; Mac-local mode sends it without a second exact-query preview.",
  }),
  cost: "No paid model API is used. Local hardware, electricity, and internet data may still have ordinary operating costs.",
});

const DEFAULT_TIMEOUT_MS = 255_000;
const CONFIG_CACHE_MS = 30_000;
export const AI_STREAM_PROTOCOL = "lumen.ai.ndjson.v1";
let configCache = null;
let configCacheGeneration = 0;
const configRequests = new Map();

const endpoint = (baseUrl, path) => `${String(baseUrl || "").replace(/\/$/, "")}${path}`;
const isRecord = (value) => Boolean(value) && typeof value === "object" && !Array.isArray(value);

/**
 * Measures the exact JSON body sent over the AI boundary. Keeping this in the
 * client module makes the composer preflight and fetch serialization share the
 * same UTF-8 contract (including quotes, backslashes, CJK, and emoji).
 */
export const aiRequestUtf8Bytes = (payload) => new TextEncoder().encode(JSON.stringify(payload)).byteLength;

export class AiClientError extends Error {
  constructor(code, message, { status = 0, requestId = null, retryAfter = null, details = null, cause } = {}) {
    super(message, { cause });
    this.name = "AiClientError";
    this.code = code;
    this.status = status;
    this.requestId = requestId;
    this.retryAfter = retryAfter;
    this.details = details;
  }

  get retryable() {
    return this.status === 0 || this.status === 408 || this.status === 429 || this.status >= 500;
  }

  get unavailable() {
    return this.code === "AI_UNAVAILABLE" || this.code === "AI_NETWORK_ERROR" || this.status === 503;
  }
}

const abortError = (message) => {
  const error = new Error(message);
  error.name = "AbortError";
  return error;
};

const MAX_AI_RESPONSE_BYTES = 4 * 1024 * 1024;
const MAX_AI_OUTPUT_CHARACTERS = 200_000;
const MAX_STREAM_LINE_BYTES = 2 * 1024 * 1024;

const readBoundedResponseText = async (response, signal) => {
  const declared = Number(response.headers?.get?.("content-length") || 0);
  if (Number.isFinite(declared) && declared > MAX_AI_RESPONSE_BYTES) {
    throw new AiClientError("AI_INVALID_RESPONSE", "The AI server response is too large.", { status: response.status });
  }
  let rejectAbort;
  const aborted = new Promise((_, reject) => {
    rejectAbort = () => reject(signal.reason || abortError("AI response read cancelled"));
    if (signal.aborted) rejectAbort();
    else signal.addEventListener("abort", rejectAbort, { once: true });
  });
  let reader;
  try {
    if (!response.body?.getReader) {
      const text = await Promise.race([response.text(), aborted]);
      if (new TextEncoder().encode(text).byteLength > MAX_AI_RESPONSE_BYTES) {
        throw new AiClientError("AI_INVALID_RESPONSE", "The AI server response is too large.", { status: response.status });
      }
      return text;
    }
    reader = response.body.getReader();
    const decoder = new TextDecoder();
    let bytes = 0;
    let text = "";
    while (true) {
      const { done, value } = await Promise.race([reader.read(), aborted]);
      if (done) break;
      bytes += value.byteLength;
      if (bytes > MAX_AI_RESPONSE_BYTES) {
        await reader.cancel("AI response exceeded byte limit").catch(() => {});
        throw new AiClientError("AI_INVALID_RESPONSE", "The AI server response is too large.", { status: response.status });
      }
      text += decoder.decode(value, { stream: true });
    }
    return text + decoder.decode();
  } finally {
    reader?.releaseLock?.();
    if (rejectAbort) signal.removeEventListener("abort", rejectAbort);
  }
};

const fetchJson = async (url, init, { signal, timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {
  if (!Number.isFinite(timeoutMs) || timeoutMs < 1_000 || timeoutMs > 315_000) {
    throw new AiClientError("INVALID_CLIENT_OPTIONS", "AI timeout must be between 1 and 315 seconds.");
  }
  const controller = new AbortController();
  let timedOut = false;
  const abortFromCaller = () => controller.abort(signal?.reason || abortError("AI request cancelled"));
  if (signal?.aborted) abortFromCaller();
  else signal?.addEventListener("abort", abortFromCaller, { once: true });
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort(abortError("AI request timed out"));
  }, timeoutMs);

  try {
    let response;
    try {
      response = await fetch(url, {
        ...init,
        signal: controller.signal,
        credentials: "same-origin",
        headers: {
          Accept: "application/json",
          ...init?.headers,
        },
      });
    } catch (error) {
      if (timedOut) throw new AiClientError("AI_CLIENT_TIMEOUT", "The AI request timed out. Please try again.", { cause: error });
      if (signal?.aborted) throw new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: error });
      throw new AiClientError(
        "AI_NETWORK_ERROR",
        "Lumen's local AI server is not reachable at this app address. Open the integrated Lumen server URL—not a static preview—and make sure the Mac server is running, then try again.",
        { cause: error },
      );
    }

    const requestId = response.headers.get("x-request-id");
    const retryAfter = response.headers.get("retry-after");
    let payload;
    try {
      const text = await readBoundedResponseText(response, controller.signal);
      payload = text ? JSON.parse(text) : {};
    } catch (error) {
      if (timedOut) throw new AiClientError("AI_CLIENT_TIMEOUT", "The AI request timed out. Please try again.", { requestId, cause: error });
      if (signal?.aborted) throw new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { requestId, cause: error });
      if (error instanceof AiClientError) throw error;
      throw new AiClientError("AI_INVALID_RESPONSE", "The AI server returned an unreadable response.", { status: response.status, requestId, cause: error });
    }

    if (!isRecord(payload)) {
      throw new AiClientError("AI_INVALID_RESPONSE", "The AI server returned an invalid response envelope.", {
        status: response.status || 502,
        requestId,
      });
    }

    if (!response.ok || payload.ok === false) {
      const serverError = payload?.error && typeof payload.error === "object" ? payload.error : {};
      throw new AiClientError(
        typeof serverError.code === "string" ? serverError.code : "AI_REQUEST_FAILED",
        typeof serverError.message === "string" ? serverError.message : "The AI request could not be completed.",
        {
          status: response.status,
          requestId: payload.requestId || requestId,
          retryAfter,
          details: Array.isArray(serverError.details) ? serverError.details : null,
        },
      );
    }
    return payload;
  } finally {
    clearTimeout(timer);
    signal?.removeEventListener("abort", abortFromCaller);
  }
};

export const clearAiConfigCache = () => {
  configCache = null;
  configCacheGeneration += 1;
  // Existing fetches are allowed to finish for their current callers, but a
  // deliberate clear must make the next caller start a fresh configuration
  // check and must prevent an older result from repopulating the cache.
  configRequests.clear();
};

const awaitWithCallerAbort = (promise, signal) => {
  if (!signal) return promise;
  if (signal.aborted) {
    return Promise.reject(new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: signal.reason }));
  }
  return new Promise((resolve, reject) => {
    const abort = () => reject(new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: signal.reason }));
    signal.addEventListener("abort", abort, { once: true });
    promise.then(resolve, reject).finally(() => signal.removeEventListener("abort", abort));
  });
};

export const getAiConfig = async ({ baseUrl = "", signal, force = false, timeoutMs = 12_000 } = {}) => {
  const normalizedBaseUrl = String(baseUrl || "").replace(/\/$/, "");
  if (!force && configCache && configCache.baseUrl === normalizedBaseUrl
    && Date.now() - configCache.cachedAt < CONFIG_CACHE_MS) return configCache.value;
  if (signal?.aborted) throw new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: signal.reason });

  // React StrictMode and multiple tutor surfaces can request the same public
  // configuration at once. Share the network operation, while keeping each
  // caller's AbortSignal local: cancelling one view must not cancel another.
  const requestKey = `${normalizedBaseUrl}\u0000${timeoutMs}`;
  let shared = configRequests.get(requestKey);
  if (!shared) {
    const generation = configCacheGeneration;
    shared = fetchJson(endpoint(normalizedBaseUrl, "/api/ai/config"), { method: "GET" }, { timeoutMs })
      .then((value) => {
        // A server that advertises a different (or no) request contract is a
        // version-skewed deployment. Fail closed before any Ready state or
        // request fitting can be based on its advertised budgets, and never
        // cache the mismatched configuration.
        if (value?.requestContract !== AI_REQUEST_CONTRACT_ID) {
          throw new AiClientError(
            "AI_CONTRACT_MISMATCH",
            "This app build and the Lumen AI server are running different versions, so AI stays off to protect your requests. Rebuild and restart the integrated Lumen server from the same source as this app, then check again.",
            { status: 409, details: [`expected request contract ${AI_REQUEST_CONTRACT_ID}`] },
          );
        }
        if (generation === configCacheGeneration) configCache = { baseUrl: normalizedBaseUrl, cachedAt: Date.now(), value };
        return value;
      })
      .finally(() => {
        if (configRequests.get(requestKey) === shared) configRequests.delete(requestKey);
      });
    configRequests.set(requestKey, shared);
  }
  return awaitWithCallerAbort(shared, signal);
};

const isValidAiSource = (source) => {
  if (!isRecord(source) || typeof source.title !== "string" || !source.title.trim() || source.title.length > 300
    || typeof source.snippet !== "string" || source.snippet.length > 1_200) return false;
  if (source.source !== undefined && (typeof source.source !== "string" || source.source.length > 100)) return false;
  if (source.publishedAt !== undefined && (typeof source.publishedAt !== "string" || source.publishedAt.length > 80)) return false;
  try {
    const url = new URL(source.url);
    return ["http:", "https:"].includes(url.protocol) && !url.username && !url.password;
  } catch { return false; }
};

export const isValidAnswerApproach = (approach) => isRecord(approach)
  && typeof approach.summary === "string"
  && Boolean(approach.summary.trim())
  && approach.summary.length <= 500
  && Array.isArray(approach.steps)
  && approach.steps.length >= 1
  && approach.steps.length <= 6
  && approach.steps.every((step) => typeof step === "string" && Boolean(step.trim()) && step.length <= 400);

const assertValidAiResponse = (response, { requireApproach = false } = {}) => {
  const usageValid = response?.usage === null || (isRecord(response?.usage)
    && ["inputTokens", "outputTokens", "totalTokens"].every((key) => Number.isSafeInteger(response.usage[key]) && response.usage[key] >= 0));
  const searchValid = isRecord(response?.webSearch)
    && typeof response.webSearch.requested === "boolean"
    && typeof response.webSearch.used === "boolean"
    && Number.isSafeInteger(response.webSearch.rounds)
    && response.webSearch.rounds >= 0;
  const sourcesValid = Array.isArray(response?.sources)
    && response.sources.length <= 8
    && response.sources.every(isValidAiSource);
  const approachValid = response?.approach === undefined
    ? !requireApproach
    : isValidAnswerApproach(response.approach);
  if (typeof response?.status === "string" && response.status !== "completed") {
    throw new AiClientError("AI_INCOMPLETE_RESPONSE", "The local model stopped before completing its response. Retry with a smaller scope.", {
      requestId: response.requestId || null,
      status: 502,
    });
  }
  if (!isRecord(response)
    || response.ok !== true
    || response.status !== "completed"
    || typeof response.requestId !== "string" || !response.requestId.trim() || response.requestId.length > 240
    || typeof response.model !== "string" || !response.model.trim() || response.model.length > 200
    || typeof response.outputText !== "string" || !response.outputText.trim() || response.outputText.length > MAX_AI_OUTPUT_CHARACTERS
    || !(response.data === null || isRecord(response.data))
    || !usageValid || !searchValid || !sourcesValid || !approachValid) {
    throw new AiClientError("AI_INVALID_RESPONSE", "The local AI server returned an invalid response envelope.", {
      requestId: typeof response?.requestId === "string" ? response.requestId.slice(0, 240) : null,
      status: 502,
    });
  }
  return response;
};

/**
 * The contract field must be part of the canonical body the composer measured;
 * appending it here after measurement would silently skew the exact UTF-8
 * budget. This assertion therefore rejects rather than repairs the payload.
 */
const assertPayloadContract = (payload) => {
  if (payload.contract !== AI_REQUEST_CONTRACT_ID) {
    throw new AiClientError(
      "INVALID_CLIENT_PAYLOAD",
      `AI request payload must declare contract ${AI_REQUEST_CONTRACT_ID} before byte fitting.`,
    );
  }
};

export const requestAi = async (payload, { baseUrl = "", signal, timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {
  if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
    throw new AiClientError("INVALID_CLIENT_PAYLOAD", "AI request payload must be an object.");
  }
  assertPayloadContract(payload);
  const response = await fetchJson(endpoint(baseUrl, "/api/ai/respond"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  }, { signal, timeoutMs });
  return assertValidAiResponse(response);
};

const streamHttpError = async (response, signal) => {
  const requestId = response.headers.get("x-request-id");
  const retryAfter = response.headers.get("retry-after");
  let payload = {};
  try {
    const text = await readBoundedResponseText(response, signal);
    payload = text ? JSON.parse(text) : {};
  } catch (error) {
    if (signal?.aborted) throw signal.reason || error;
    if (error instanceof AiClientError) throw error;
    throw new AiClientError("AI_INVALID_RESPONSE", "The AI server returned an unreadable error response.", {
      status: response.status || 502,
      requestId,
      cause: error,
    });
  }
  const serverError = isRecord(payload?.error) ? payload.error : {};
  throw new AiClientError(
    typeof serverError.code === "string" ? serverError.code : "AI_REQUEST_FAILED",
    typeof serverError.message === "string" ? serverError.message : "The AI request could not be completed.",
    {
      status: response.status,
      requestId: typeof payload.requestId === "string" ? payload.requestId : requestId,
      retryAfter,
      details: Array.isArray(serverError.details) ? serverError.details : null,
    },
  );
};

const hasOnlyEventKeys = (event, allowed) => Object.keys(event).every((key) => allowed.includes(key));
const validRequestId = (value) => typeof value === "string" && Boolean(value.trim()) && value.length <= 240;

/**
 * Streams a Markdown AI response from the same-origin local server.
 *
 * `onDelta` receives answer text only; `onEvent` receives metadata events. If
 * both are supplied, delta events are routed only to `onDelta` to prevent a UI
 * from appending each token twice. Each callback is awaited, making it the
 * browser-side backpressure boundary.
 */
export const requestAiStream = async (payload, {
  baseUrl = "",
  signal,
  timeoutMs = DEFAULT_TIMEOUT_MS,
  idleTimeoutMs = 45_000,
  onEvent,
  onDelta,
  onStatus,
  onSources,
} = {}) => {
  if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
    throw new AiClientError("INVALID_CLIENT_PAYLOAD", "AI request payload must be an object.");
  }
  assertPayloadContract(payload);
  if (!Number.isFinite(timeoutMs) || timeoutMs < 1_000 || timeoutMs > 315_000
    || !Number.isFinite(idleTimeoutMs) || idleTimeoutMs < 100 || idleTimeoutMs > 120_000) {
    throw new AiClientError("INVALID_CLIENT_OPTIONS", "AI streaming deadlines are outside the supported range.");
  }

  const controller = new AbortController();
  let timedOut = false;
  const abortFromCaller = () => controller.abort(signal?.reason || abortError("AI request cancelled"));
  if (signal?.aborted) abortFromCaller();
  else signal?.addEventListener("abort", abortFromCaller, { once: true });
  const overallTimer = setTimeout(() => {
    timedOut = true;
    controller.abort(abortError("AI request timed out"));
  }, timeoutMs);

  let reader = null;
  try {
    let response;
    try {
      response = await fetch(endpoint(baseUrl, "/api/ai/respond/stream"), {
        method: "POST",
        credentials: "same-origin",
        headers: {
          Accept: "application/x-ndjson",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });
    } catch (error) {
      if (timedOut) throw new AiClientError("AI_CLIENT_TIMEOUT", "The AI request timed out. Please try again.", { cause: error });
      if (signal?.aborted) throw new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: error });
      throw new AiClientError(
        "AI_NETWORK_ERROR",
        "Lumen's local AI server is not reachable at this app address. Open the integrated Lumen server URL—not a static preview—and make sure the Mac server is running, then try again.",
        { cause: error },
      );
    }
    if (!response.ok) await streamHttpError(response, controller.signal);
    const declaredLength = Number(response.headers.get("content-length") || 0);
    if (Number.isFinite(declaredLength) && declaredLength > MAX_AI_RESPONSE_BYTES) {
      throw new AiClientError("AI_INVALID_RESPONSE", "The AI stream exceeded the safe response limit.", {
        status: response.status || 502,
        requestId: response.headers.get("x-request-id"),
      });
    }
    const mediaType = String(response.headers.get("content-type") || "").split(";", 1)[0].trim().toLowerCase();
    if (mediaType !== "application/x-ndjson") {
      throw new AiClientError("AI_INVALID_RESPONSE", "The AI server did not return the expected streaming protocol.", {
        status: response.status || 502,
        requestId: response.headers.get("x-request-id"),
      });
    }
    const advertisedProtocol = response.headers.get("x-lumen-stream-protocol");
    if (advertisedProtocol && advertisedProtocol !== AI_STREAM_PROTOCOL) {
      throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI server uses an incompatible streaming protocol.", { status: 502 });
    }
    if (!response.body?.getReader) {
      throw new AiClientError("AI_STREAM_UNSUPPORTED", "This browser cannot read incremental AI responses.", { status: 0 });
    }

    reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8", { fatal: true });
    const encoder = new TextEncoder();
    let totalBytes = 0;
    let buffered = "";
    let lineNumber = 0;
    let start = null;
    let approach = null;
    let completed = null;
    let terminal = false;
    let expectedSequence = 0;
    let streamedText = "";
    const streamedSources = [];

    const invoke = async (callback, ...args) => {
      if (typeof callback !== "function") return;
      try {
        await callback(...args);
      } catch (error) {
        controller.abort(error);
        throw new AiClientError("AI_STREAM_CALLBACK_ERROR", "The app could not process an AI stream update.", { cause: error });
      }
    };

    const processEvent = async (event) => {
      lineNumber += 1;
      if (!isRecord(event) || typeof event.type !== "string") {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", `AI stream event ${lineNumber} is malformed.`, { status: 502 });
      }
      if (terminal) {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream continued after its terminal event.", { status: 502 });
      }
      if (!start && event.type !== "start") {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream did not begin with a start event.", { status: 502 });
      }
      if (start && !approach && !["start", "approach", "error"].includes(event.type)) {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream did not declare its answer approach before content or progress.", { status: 502, requestId: start.requestId });
      }
      if (start && event.type !== "start" && event.requestId !== start.requestId) {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "AI stream request identifiers do not match.", { status: 502, requestId: start.requestId });
      }

      if (event.type === "start") {
        if (start || !hasOnlyEventKeys(event, ["type", "protocol", "requestId", "model", "responseFormat", "responseProfile", "startedAt"])
          || event.protocol !== AI_STREAM_PROTOCOL || !validRequestId(event.requestId)
          || typeof event.model !== "string" || !event.model.trim() || event.model.length > 200
          || !["markdown", "structured"].includes(event.responseFormat)
          || !["fast", "balanced", "deep"].includes(event.responseProfile)
          || typeof event.startedAt !== "string" || !Number.isFinite(Date.parse(event.startedAt))) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream start event is invalid.", { status: 502 });
        }
        start = event;
        const headerRequestId = response.headers.get("x-request-id");
        if (headerRequestId && headerRequestId !== event.requestId) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream request identifier does not match its response header.", { status: 502 });
        }
        await invoke(onEvent, event);
        return;
      }
      if (event.type === "approach") {
        if (approach || !hasOnlyEventKeys(event, ["type", "requestId", "approach"]) || !isValidAnswerApproach(event.approach)) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream approach event is invalid.", { status: 502, requestId: start.requestId });
        }
        approach = event.approach;
        await invoke(onEvent, event);
        return;
      }
      if (event.type === "phase") {
        if (!hasOnlyEventKeys(event, ["type", "requestId", "phase", "message"])
          || !["preparing", "searching", "generating", "validating"].includes(event.phase)
          || typeof event.message !== "string" || !event.message.trim() || event.message.length > 240) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream phase event is invalid.", { status: 502, requestId: start.requestId });
        }
        await invoke(onEvent, event);
        await invoke(onStatus, event.message, event);
        return;
      }
      if (event.type === "heartbeat") {
        if (!hasOnlyEventKeys(event, ["type", "requestId", "at"])
          || typeof event.at !== "string" || !Number.isFinite(Date.parse(event.at))) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream heartbeat is invalid.", { status: 502, requestId: start.requestId });
        }
        await invoke(onEvent, event);
        return;
      }
      if (event.type === "source") {
        if (!hasOnlyEventKeys(event, ["type", "requestId", "index", "source"])
          || event.index !== streamedSources.length + 1 || !isValidAiSource(event.source)
          || streamedSources.some((source) => source.url === event.source.url)) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream source event is invalid.", { status: 502, requestId: start.requestId });
        }
        streamedSources.push(event.source);
        await invoke(onEvent, event);
        await invoke(onSources, [...streamedSources], event);
        // Compatibility metadata for UI consumers that render source lists as
        // a single event rather than individual source records.
        await invoke(onEvent, { type: "sources", requestId: event.requestId, sources: [...streamedSources] });
        return;
      }
      if (event.type === "delta") {
        if (!hasOnlyEventKeys(event, ["type", "requestId", "sequence", "text"])
          || start.responseFormat !== "markdown" || event.sequence !== expectedSequence
          || typeof event.text !== "string" || !event.text || event.text.length > 65_536) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream text delta is invalid or out of order.", { status: 502, requestId: start.requestId });
        }
        expectedSequence += 1;
        streamedText += event.text;
        if (streamedText.length > MAX_AI_OUTPUT_CHARACTERS) {
          throw new AiClientError("AI_INVALID_RESPONSE", "The streamed AI answer exceeded the safe output limit.", { status: 502, requestId: start.requestId });
        }
        if (typeof onDelta === "function") await invoke(onDelta, event.text, event);
        else await invoke(onEvent, event);
        return;
      }
      if (event.type === "complete") {
        if (!hasOnlyEventKeys(event, ["type", "requestId", "response"]) || !approach) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream completion event is invalid.", { status: 502, requestId: start.requestId });
        }
        const finalResponse = assertValidAiResponse(event.response, { requireApproach: true });
        if (finalResponse.requestId !== start.requestId
          || JSON.stringify(finalResponse.approach) !== JSON.stringify(approach)
          || JSON.stringify(finalResponse.sources) !== JSON.stringify(streamedSources)
          || (start.responseFormat === "markdown" && finalResponse.outputText !== streamedText)) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The final AI response does not match its streamed content.", { status: 502, requestId: start.requestId });
        }
        terminal = true;
        completed = finalResponse;
        await invoke(onEvent, event);
        return;
      }
      if (event.type === "error") {
        const errorValue = event.error;
        if (!hasOnlyEventKeys(event, ["type", "requestId", "status", "error", "retryAfter"])
          || !isRecord(errorValue) || !hasOnlyEventKeys(errorValue, ["code", "message"])
          || typeof errorValue.code !== "string" || !errorValue.code.trim() || errorValue.code.length > 100
          || typeof errorValue.message !== "string" || !errorValue.message.trim() || errorValue.message.length > 1_000
          || !Number.isSafeInteger(event.status) || event.status < 400 || event.status > 599
          || (event.retryAfter !== undefined && (typeof event.retryAfter !== "string" || event.retryAfter.length > 20))) {
          throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI stream error event is invalid.", { status: 502, requestId: start.requestId });
        }
        terminal = true;
        await invoke(onEvent, event);
        throw new AiClientError(errorValue.code, errorValue.message, {
          status: event.status,
          requestId: start.requestId,
          retryAfter: event.retryAfter || null,
        });
      }
      throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", `Unsupported AI stream event type: ${event.type}.`, { status: 502, requestId: start.requestId });
    };

    const readNext = async () => {
      let idleTimer = null;
      let abortHandler = null;
      const interrupted = new Promise((_resolve, reject) => {
        abortHandler = () => reject(controller.signal.reason || abortError("AI stream cancelled"));
        if (controller.signal.aborted) abortHandler();
        else controller.signal.addEventListener("abort", abortHandler, { once: true });
        idleTimer = setTimeout(() => reject(new AiClientError("AI_STREAM_IDLE_TIMEOUT", "The local AI stopped sending updates. Please retry.", {
          requestId: start?.requestId || null,
          status: 504,
        })), idleTimeoutMs);
      });
      try {
        return await Promise.race([reader.read(), interrupted]);
      } finally {
        if (idleTimer) clearTimeout(idleTimer);
        if (abortHandler) controller.signal.removeEventListener("abort", abortHandler);
      }
    };

    while (true) {
      const { done, value } = await readNext();
      if (done) break;
      totalBytes += value.byteLength;
      if (totalBytes > MAX_AI_RESPONSE_BYTES) {
        throw new AiClientError("AI_INVALID_RESPONSE", "The AI stream exceeded the safe response limit.", { status: 502, requestId: start?.requestId || null });
      }
      buffered += decoder.decode(value, { stream: true });
      let newline = buffered.indexOf("\n");
      while (newline >= 0) {
        const line = buffered.slice(0, newline).replace(/\r$/, "");
        buffered = buffered.slice(newline + 1);
        if (line.trim()) {
          if (encoder.encode(line).byteLength > MAX_STREAM_LINE_BYTES) {
            throw new AiClientError("AI_INVALID_RESPONSE", "An AI stream event exceeded the safe line limit.", { status: 502, requestId: start?.requestId || null });
          }
          let event;
          try { event = JSON.parse(line); } catch (error) {
            throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI server returned invalid streamed JSON.", { status: 502, requestId: start?.requestId || null, cause: error });
          }
          await processEvent(event);
        }
        newline = buffered.indexOf("\n");
      }
      if (encoder.encode(buffered).byteLength > MAX_STREAM_LINE_BYTES) {
        throw new AiClientError("AI_INVALID_RESPONSE", "An AI stream event exceeded the safe line limit.", { status: 502, requestId: start?.requestId || null });
      }
    }
    buffered += decoder.decode();
    const trailing = buffered.replace(/\r$/, "");
    if (trailing.trim()) {
      let event;
      try { event = JSON.parse(trailing); } catch (error) {
        throw new AiClientError("AI_STREAM_PROTOCOL_ERROR", "The AI server returned invalid streamed JSON.", { status: 502, requestId: start?.requestId || null, cause: error });
      }
      await processEvent(event);
    }
    if (!completed || !terminal) {
      throw new AiClientError("AI_STREAM_INCOMPLETE", "The local AI stream ended before a validated answer was completed.", {
        status: 502,
        requestId: start?.requestId || null,
      });
    }
    return completed;
  } catch (error) {
    reader?.cancel?.("AI stream stopped").catch(() => {});
    if (error instanceof AiClientError) throw error;
    if (timedOut) throw new AiClientError("AI_CLIENT_TIMEOUT", "The AI request timed out. Please try again.", { cause: error });
    if (signal?.aborted) throw new AiClientError("AI_CANCELLED", "The AI request was cancelled.", { cause: error });
    throw new AiClientError("AI_INVALID_RESPONSE", "The AI server returned an unreadable stream.", { status: 502, cause: error });
  } finally {
    clearTimeout(overallTimer);
    signal?.removeEventListener("abort", abortFromCaller);
    reader?.releaseLock?.();
  }
};

export const requestStructuredAi = async (payload, options) => {
  const response = await requestAi({ ...payload, responseFormat: "structured" }, options);
  if (!response.data || typeof response.data !== "object") {
    throw new AiClientError("AI_CONTRACT_ERROR", "AI did not return the expected structured learning content.", {
      requestId: response.requestId || null,
    });
  }
  return response;
};

/**
 * Pairs this browser with a pairing-protected Lumen server. The server
 * responds with an HttpOnly session cookie; no token is ever exposed to
 * JavaScript. Success clears the configuration cache so the next check
 * reflects the active session.
 */
export const pairAiSession = async (code, { baseUrl = "", signal, timeoutMs = 15_000 } = {}) => {
  const normalized = typeof code === "string" ? code.trim() : "";
  if (!normalized || normalized.length > 200) {
    throw new AiClientError("INVALID_PAIRING_CODE", "Enter the pairing code shown by the Lumen server operator.");
  }
  const response = await fetchJson(endpoint(baseUrl, "/api/auth/pair"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ code: normalized }),
  }, { signal, timeoutMs });
  if (response.ok !== true) {
    throw new AiClientError("AI_INVALID_RESPONSE", "The pairing response was invalid.", { status: 502 });
  }
  clearAiConfigCache();
  return { expiresAt: typeof response.expiresAt === "string" ? response.expiresAt : null };
};

/**
 * Runs one explicit same-origin search through the server-owned SearXNG
 * gateway. Calling this function is the per-search consent action; it accepts
 * no URL, engine, provider, or model option.
 */
export const searchLocalWeb = async (query, { baseUrl = "", signal, timeoutMs = 15_000 } = {}) => {
  if (typeof query !== "string") {
    throw new AiClientError("INVALID_SEARCH_QUERY", "Search query must be text.");
  }
  const normalized = query.replace(/\s+/g, " ").trim();
  if (!normalized || normalized.length > 240
    || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/.test(normalized)
    || /[\p{Default_Ignorable_Code_Point}\u115f\u1160\u3164\uffa0]/u.test(normalized)
    || /(^|\s)[!:]\S+/.test(normalized)) {
    throw new AiClientError("INVALID_SEARCH_QUERY", "Search query must contain 1 to 240 valid characters.");
  }
  const response = await fetchJson(endpoint(baseUrl, "/api/local-search"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query: normalized }),
  }, { signal, timeoutMs });
  const allowedKeys = new Set(["ok", "requestId", "query", "results"]);
  const resultsValid = Array.isArray(response.results) && response.results.length <= 8 && response.results.every((result) => {
    if (!isRecord(result)
      || Object.keys(result).some((key) => !["title", "url", "snippet", "source", "publishedAt"].includes(key))
      || typeof result.title !== "string" || !result.title.trim() || result.title.length > 300
      || typeof result.snippet !== "string" || !result.snippet.trim() || result.snippet.length > 1_200
      || (result.source !== undefined && (typeof result.source !== "string" || result.source.length > 100))
      || (result.publishedAt !== undefined && (typeof result.publishedAt !== "string" || result.publishedAt.length > 80))) return false;
    try {
      const url = new URL(result.url);
      return ["http:", "https:"].includes(url.protocol) && !url.username && !url.password;
    } catch { return false; }
  });
  if (Object.keys(response).some((key) => !allowedKeys.has(key))
    || response.ok !== true
    || typeof response.requestId !== "string" || !response.requestId.trim() || response.requestId.length > 240
    || response.query !== normalized
    || !resultsValid) {
    throw new AiClientError("AI_INVALID_RESPONSE", "The local search gateway returned an invalid response envelope.", {
      requestId: typeof response.requestId === "string" ? response.requestId.slice(0, 240) : null,
      status: 502,
    });
  }
  return response;
};

/**
 * Fits long local notes into a request budget while making the omission visible
 * to the model. Callers should prefer a selected section over whole-document
 * clipping whenever possible.
 */
export const clipAiContext = (value, maximumCharacters = 16_000) => {
  if (!Number.isSafeInteger(maximumCharacters) || maximumCharacters < 1_000) {
    throw new AiClientError("INVALID_CLIENT_OPTIONS", "AI context limit must be at least 1,000 characters.");
  }
  const text = typeof value === "string" ? value.replace(/\r\n?/g, "\n").trim() : "";
  if (text.length <= maximumCharacters) return text;
  const marker = "\n\n[… middle of source omitted by the app …]\n\n";
  const available = maximumCharacters - marker.length;
  const beginning = Math.ceil(available * 0.68);
  return `${text.slice(0, beginning)}${marker}${text.slice(text.length - (available - beginning))}`;
};

export const aiClient = Object.freeze({
  getConfig: getAiConfig,
  pair: pairAiSession,
  request: requestAi,
  requestStream: requestAiStream,
  stream: requestAiStream,
  requestStructured: requestStructuredAi,
  searchWeb: searchLocalWeb,
  clipContext: clipAiContext,
  clearConfigCache: clearAiConfigCache,
});
